### ISSUE TITLE
Error with Volatility2

### ISSUE THREAD

**Issue by belveruski** [CrowdStrike/SuperMem#2]
Hi,

When i run the script, i have the following error with Volatility 2:
```text
ERROR: Cant find KDGB for Volatility2 caused by error in regex
```

Here is my command with the options:
```bash
$ python3 winSuperMem.py -f cridex.vmem -o output -p WinXPSP2x86 -tt 3
```
Thanks for this great tool.

**Comment by jdlovato** [comment]
What do you get if you run imageinfo on the memory image with Volatility 2? The script essentially is running that and parsing the profile, KDGB, and DTB from that output.

**Comment by belveruski** [comment]
Thanks for the reply,

I get this:
```bash
$ vol2 -f cridex.vmem imageinfo
```
```text
Volatility Foundation Volatility Framework 2.6.1
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : WinXPSP2x86, WinXPSP3x86 (Instantiated with WinXPSP2x86)
                     AS Layer1 : IA32PagedMemoryPae (Kernel AS)
                     AS Layer2 : FileAddressSpace (/home/vagrant/Tools/cridex.vmem)
                      PAE type : PAE
                           DTB : 0x2fe000L
                          KDBG : 0x80545ae0L
          Number of Processors : 1
     Image Type (Service Pack) : 3
                KPCR for CPU 0 : 0xffdff000L
             KUSER_SHARED_DATA : 0xffdf0000L
           Image date and time : 2012-07-22 02:45:08 UTC+0000
     Image local date and time : 2012-07-21 22:45:08 -0400
```

**Comment by jdlovato** [comment]
I have tested the regex and it does work correctly with this output. Would this be the VMEM file you are working with?
http://files.sempersecurus.org/dumps/cridex_memdump.zip

I was able to run the script successfully on this memory dump with the exact command you used above. What happens if you remove the profile switch "-p"?

**Comment by belveruski** [comment]
@jdlovato Yes, this is the file I am working on.

If i remove the profile switch "-p" i have this error:
```txt
ERROR: Cant find profile for Volatility2
```

**Comment by belveruski** [comment]
I reinstall all the requirements and it works now, thanks for your help @jdlovato
