### ISSUE TITLE
Created a docker container around this

### ISSUE THREAD

**Issue by takov751** [CrowdStrike/SuperMem#3]
I just created a docker container around this tool. It is only a dirty version. Needs optimalization ( env variables, unnecessary files removed, etc). Need testing as well, but so far seems working 

https://github.com/takov751/SuperMem-docker

Any question, just write here or on the repo. It's not something I will actively maintain, just a wrapping.

**Comment by shawndwells** [comment]
Why not submit a pull request? :)

We (CrowdStrike) maintain https://quay.io/organization/crowdstrike and also some DockerHub images. Might make sense to publish a SuperMem container image there.

**Comment by takov751** [comment]
Because it's no where near ready and just working and not implemented some hardening and optimalization which needed to make it smaller and more secure. However if I have time and got to that point I might do that 👌 @shawndwells
